[parity]
chain = "spec.json"
base_path = "/tmp/parity/OCIoT-Chain/node0"
[network]
port = 30300
[rpc]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts", "private"]
[websockets]
port = 8450
[account]
password = ["node.pwds"]
unlock = ["0xa053beb738b5be3d2c934e0c027d243e1dbfb9a1", "0x9660e541f793360d64dc8218fdc14dce5cd40ef0"]
[mining]
engine_signer = "0xa053beb738b5be3d2c934e0c027d243e1dbfb9a1"
reseal_on_txs = "none"