[parity]
chain = "spec.json"
base_path = "/tmp/parity/OCIoT-Chain/node1"
[network]
port = 30301
[rpc]
port = 8541
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts", "private"]
[websockets]
port = 8451
[ipc]
disable = true
[account]
password = ["node.pwds"]
unlock = ["0xcb41ef1c2dbd54e3f045a0bedff20e6090708c8d"]
[mining]
engine_signer = "0xcb41ef1c2dbd54e3f045a0bedff20e6090708c8d"
reseal_on_txs = "none"